### ISSUE TITLE
resources

### ISSUE THREAD

**Issue by xdcui-nlp** [salesforce/fewshot_absa#3]
Hi, the semeval data I find according to the readme is in xml format, then I find that the code read the data in json format and I don't find the laptops_test data, can you provide me with the resources folder? I'd appreciate it!

**Comment by ehosseiniasl** [comment]
thanks for noting this.
the code for converting the xml to json is added. 
please refer to updated preprocessing in README

**Comment by xdcui-nlp** [comment]
> thanks for noting this. the code for converting the xml to json is added. please refer to updated preprocessing in README

thank you!
