### ISSUE TITLE
semeval16 trial data

### ISSUE THREAD

**Issue by xdcui-nlp** [salesforce/fewshot_absa#4]
Hi, I would like to ask what is the trial in semeval16 in your data, because I can't find trial in the link you gave, only gold test and phase A test and phase B test, is it one of the test as trial or is it something else? I look forward to hearing from you, thank you very much!

**Comment by ehosseiniasl** [comment]
Hi,
Below are the links to trial data for Semeval14 and Semeval16

Semeval14:
https://alt.qcri.org/semeval2014/task4/data/uploads/laptops-trial.xml
https://alt.qcri.org/semeval2014/task4/data/uploads/restaurants-trial.xml

Semeval16:
https://alt.qcri.org/semeval2016/task5/data/uploads/trial-data/english-trial/restaurants_trial_english_sl.xml
https://alt.qcri.org/semeval2016/task5/data/uploads/trial-data/english-trial/laptops_trial_english_sl.xml

**Comment by xdcui-nlp** [comment]
> Hi, Below are the links to trial data for Semeval14 and Semeval16
> 
> Semeval14: https://alt.qcri.org/semeval2014/task4/data/uploads/laptops-trial.xml https://alt.qcri.org/semeval2014/task4/data/uploads/restaurants-trial.xml
> 
> Semeval16: https://alt.qcri.org/semeval2016/task5/data/uploads/trial-data/english-trial/restaurants_trial_english_sl.xml https://alt.qcri.org/semeval2016/task5/data/uploads/trial-data/english-trial/laptops_trial_english_sl.xml

thank you , but semeval16  also has sub2

**Comment by ehosseiniasl** [comment]
yes
we only used subtask-1 in our paper.

**Comment by xdcui-nlp** [comment]
> yes we only used subtask-1 in our paper.

Okay, which is the test, gold or phase A or phase B?

**Comment by ehosseiniasl** [comment]
the difference between phase A and B is in providing annotation in phase B to predict polarity only.

**Comment by ehosseiniasl** [comment]
you can use gold annotations

**Comment by xdcui-nlp** [comment]
> you can use gold annotations
Okey, thank you
