### ISSUE TITLE
data tags

### ISSUE THREAD

**Issue by xdcui-nlp** [salesforce/fewshot_absa#5]
Hi, I would like to ask about the data tags, why <|review|> and <|endofreview|> are a pair, including <|category|> and <|endofcategory|>, <|term|> and <|endofterm|>, but <|endoftext|> and <|endoftext|> are a pair, not <|text|> and <|endoftext|> are a pair.

**Comment by ehosseiniasl** [comment]
Hi, the use of <|endoftext|> at the beginning and end of sequence is to match to the pretraining data of gpt2.

**Comment by xdcui-nlp** [comment]
> Hi, the use of <|endoftext|> at the beginning and end of sequence is to match to the pretraining data of gpt2.

ok,thank you for your reply
